CREATE TABLE EMPLOYE
(
    MATRICULE NUMBER(5),
    NOM VARCHAR(20) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    FONCTION VARCHAR (20) NOT NULL,
    CIN VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) ,
    TEL VARCHAR(15) NOT NULL,
    SALAIRE NUMBER(6,2) NOT NULL,
    PHOTO FILE ,
    CONSTRAINT PK_EMPLOYE PRIMARY KEY MATRICULE
);

CREATE TABLE ADMINS
(
    MATRICULE NUMBER(5),
    NOM VARCHAR(20 ) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TEL VARCHAR(15) NOT NULL,
    MOTS_DE_PASSE VARCHAR (20) NOT NULL,
    PHOTO FILE ,
    CONSTRAINT PK_ADMINS PRIMARY KEY MATRICULE 
);

CREATE TABLE RESTAURANTS 
(
    ID NUMBER(2),
    NOM VARCHAR(30),
    ADRESSE VARCHAR(50),
    TABLES NUMBER(3),
    CONSTRAINT PK_RESTAURANTS PRIMARY KEY ID
);

CREATE TABLE STOCKS
(
    GENRE VARCHAR(10),
    QTE NUMBER(10) CHECK QTE > 0,
    CONSTRAINT PK_STOCKS PRIMARY KEY GENRE
);

CREATE TABLE MENU
(
    ID NUMBER(2),
    NOM VARCHAR(10) NOT NULL,
    PRIX NUMBER(4.2) NOT NULL,
)