CREATE TABLE EMPLOYE
(
    MATRICULE NUMBER(5),
    NOM VARCHAR(20) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    FONCTION VARCHAR (20) NOT NULL,
    CIN VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) ,
    TEL VARCHAR(15) NOT NULL,
    SALAIRE NUMBER(6,2) NOT NULL,
    PHOTO FILE ,
    CONSTRAINT PK_EMPLOYE PRIMARY KEY MATRICULE
);

CREATE TABLE ADMINS
(
    MATRICULE NUMBER(5),
    NOM VARCHAR(20 ) NOT NULL,
    PRENOM VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TEL VARCHAR(15) NOT NULL,
    MOTS_DE_PASSE VARCHAR (20) NOT NULL,
    CONSTRAINT PK_ADMINS PRIMARY KEY MATRICULE 
);

CREATE TABLE RESTAURANTS 
(
    ID NUMBER(2),
    NOM VARCHAR(30),
    ADRESSE VARCHAR(50),
    TABLES NUMBER(3),
    CONSTRAINT PK_RESTAURANTS PRIMARY KEY ID
);

CREATE TABLE PRODUIT
(
    NO NUMBER(2),
    NOM VARCHAR(10),
    CATEGORY VARCHAR(10),
    CONSTRAINT PK_PRODUIT PRIMARY KEY NO
);

CREATE TABLE STOCK 
(
    NO NUMBER(2),
    PROD_NO NUMBER(2),
    QTE_STOCK NUMBER(4),
    CONSTRAINT PK_STOCK PRIMARY KEY NO,
    CONSTRAINT FK_STOCK FOREIGN KEY REFERENCES PRODUIT(NO)
);

CREATE TABLE MENU 
(
    NO NUMBER(2),
    NOM VARCHAR(10),
    PRIX NUMBER(3,2),
    CONSTRAINT PK_MENU PRIMARY KEY NO
);

CREATE TABLE QTE_MENU_PRODUIT
(
    MENU_NO NUMBER(2) FOREIGN KEY REFERENCES MENU(NO),
    PRD_NO NUMBER(2) FOREIGN KEY REFERENCES PRODUIT(NO),
    QTE NUMBER(3) NOT NULL,
    CONSTRAINT PK_QTE_MENU_PRODUIT PRIMARY KEY MENU_NO,PRD_NO 
);

CREATE TABLE COMMANDE 
(
    NO NUMBER(7),
    CLIENT_NOM VARCHAR(25),
    DATE_COMMANDE DATE,
    CONSTRAINT PK_COMMANDE PRIMARY KEY (NO)
);


CREATE TABLE LIGNE_COMMANDE
(
    COMMANDE_NO NUMBER(7),
    MENU_NO  NUMBER(2),
    QTE NUMBER(9),
    CONSTRAINT FK_COMMANDE FOREIGN KEY REFERENCES COMMANDE(NO),
    CONSTRAINT FK_MENU FOREIGN KEY REFERENCES MENU(NO),
    CONSTRAINT PK_LIGNE_COMMANDE PRIMARY KEY COMMANDE_NO,MENU_NO
);

CREATE TABLE DEPENSE
(
    NO NUMBER(7),
    DESCRI VARCHAR(30),
    PRIX NUMBER(6,2),
    CONSTRAINT PK_DEPENSE PRIMARY KEY NO
);

CREATE TABLE RECETTE
(
    NO NUMBER(7),
    DESCRI VARCHAR(30),
    PRIX NUMBER(6,2),
    CONSTRAINT PK_RECETTE PRIMARY KEY NO
);
